# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.avgsSpinBox = QtWidgets.QSpinBox(self.widget)
        self.avgsSpinBox.setObjectName("avgsSpinBox")
        self.gridLayout_2.addWidget(self.avgsSpinBox, 2, 1, 1, 1)
        self.intSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intSpinBox.sizePolicy().hasHeightForWidth())
        self.intSpinBox.setSizePolicy(sizePolicy)
        self.intSpinBox.setObjectName("intSpinBox")
        self.gridLayout_2.addWidget(self.intSpinBox, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.connectBox = QtWidgets.QCheckBox(self.widget)
        self.connectBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectBox.sizePolicy().hasHeightForWidth())
        self.connectBox.setSizePolicy(sizePolicy)
        self.connectBox.setCheckable(True)
        self.connectBox.setTristate(False)
        self.connectBox.setObjectName("connectBox")
        self.gridLayout_2.addWidget(self.connectBox, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.calcPLQEButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcPLQEButton.sizePolicy().hasHeightForWidth())
        self.calcPLQEButton.setSizePolicy(sizePolicy)
        self.calcPLQEButton.setObjectName("calcPLQEButton")
        self.verticalLayout.addWidget(self.calcPLQEButton)
        self.PLQEdisplay = QtWidgets.QLineEdit(self.widget)
        self.PLQEdisplay.setEnabled(True)
        self.PLQEdisplay.setReadOnly(True)
        self.PLQEdisplay.setObjectName("PLQEdisplay")
        self.verticalLayout.addWidget(self.PLQEdisplay)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.calibBrowseButton = QtWidgets.QPushButton(self.widget)
        self.calibBrowseButton.setObjectName("calibBrowseButton")
        self.gridLayout.addWidget(self.calibBrowseButton, 0, 2, 1, 1)
        self.calibFileDisp = QtWidgets.QLineEdit(self.widget)
        self.calibFileDisp.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibFileDisp.sizePolicy().hasHeightForWidth())
        self.calibFileDisp.setSizePolicy(sizePolicy)
        self.calibFileDisp.setText("")
        self.calibFileDisp.setPlaceholderText("")
        self.calibFileDisp.setObjectName("calibFileDisp")
        self.gridLayout.addWidget(self.calibFileDisp, 0, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.widget)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 3, 2, 1, 1)
        self.folderDisplay = QtWidgets.QLineEdit(self.widget)
        self.folderDisplay.setEnabled(False)
        self.folderDisplay.setAutoFillBackground(False)
        self.folderDisplay.setReadOnly(True)
        self.folderDisplay.setObjectName("folderDisplay")
        self.gridLayout.addWidget(self.folderDisplay, 2, 1, 1, 1)
        self.filenameDisplay = QtWidgets.QLineEdit(self.widget)
        self.filenameDisplay.setObjectName("filenameDisplay")
        self.gridLayout.addWidget(self.filenameDisplay, 3, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.widget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.acqBckgButton = QtWidgets.QPushButton(self.groupBox)
        self.acqBckgButton.setObjectName("acqBckgButton")
        self.gridLayout_8.addWidget(self.acqBckgButton, 0, 0, 1, 1)
        self.acqINButton = QtWidgets.QPushButton(self.groupBox)
        self.acqINButton.setObjectName("acqINButton")
        self.gridLayout_8.addWidget(self.acqINButton, 1, 0, 1, 1)
        self.acqLaserButton = QtWidgets.QPushButton(self.groupBox)
        self.acqLaserButton.setObjectName("acqLaserButton")
        self.gridLayout_8.addWidget(self.acqLaserButton, 0, 1, 1, 1)
        self.acqOUTButton = QtWidgets.QPushButton(self.groupBox)
        self.acqOUTButton.setObjectName("acqOUTButton")
        self.gridLayout_8.addWidget(self.acqOUTButton, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.INPLthresh = QtWidgets.QDoubleSpinBox(self.widget)
        self.INPLthresh.setObjectName("INPLthresh")
        self.gridLayout_6.addWidget(self.INPLthresh, 2, 1, 1, 1)
        self.OUTPLthresh = QtWidgets.QDoubleSpinBox(self.widget)
        self.OUTPLthresh.setObjectName("OUTPLthresh")
        self.gridLayout_6.addWidget(self.OUTPLthresh, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 1, 2, 1, 1)
        self.laserthresh = QtWidgets.QDoubleSpinBox(self.widget)
        self.laserthresh.setObjectName("laserthresh")
        self.gridLayout_6.addWidget(self.laserthresh, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_6.addWidget(self.pushButton, 0, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 4)
        self.groupBox_LaserPlot = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_LaserPlot.sizePolicy().hasHeightForWidth())
        self.groupBox_LaserPlot.setSizePolicy(sizePolicy)
        self.groupBox_LaserPlot.setObjectName("groupBox_LaserPlot")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_LaserPlot)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_5.addWidget(self.splitter, 3, 0, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.acqBckgButton.clicked.connect(self.acquireBckgSlot)
        self.calcPLQEButton.clicked.connect(self.calcPLQESlot)
        self.acqINButton.clicked.connect(self.acquireINSlot)
        self.acqOUTButton.clicked.connect(self.acquireOUTSlot)
        # self.connectBox.toggled['bool'].connect(MainWindow.connectSpecSlot)
        self.saveButton.clicked.connect(self.savefileSlot)
        self.calibBrowseButton.clicked.connect(self.calibBrowseSlot)
        self.acqLaserButton.clicked.connect(self.acquireLaserSlot)
        self.browseButton.clicked.connect(self.browseSlot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Integration (ms)"))
        self.label_4.setText(_translate("MainWindow", "Avgs"))
        self.label_5.setText(_translate("MainWindow", "USB4000"))
        self.connectBox.setText(_translate("MainWindow", "Connect"))
        self.calcPLQEButton.setText(_translate("MainWindow", "Calculate PLQE"))
        self.calibBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Filename"))
        self.label.setText(_translate("MainWindow", "Folder"))
        self.label_7.setText(_translate("MainWindow", "Calibration"))
        self.groupBox.setTitle(_translate("MainWindow", "Acquisition"))
        self.acqBckgButton.setText(_translate("MainWindow", "Acquire bckg"))
        self.acqINButton.setText(_translate("MainWindow", "Sample in beam"))
        self.acqLaserButton.setText(_translate("MainWindow", "Laser in"))
        self.acqOUTButton.setText(_translate("MainWindow", "Sample out of beam"))
        self.label_6.setText(_translate("MainWindow", "Laser Thresh"))
        self.label_8.setText(_translate("MainWindow", "INPL Thresh"))
        self.label_9.setText(_translate("MainWindow", "OUTPL Thresh"))
        self.pushButton.setText(_translate("MainWindow", "Signal Detect"))
        self.groupBox_LaserPlot.setTitle(_translate("MainWindow", "Spectra"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

