# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(841, 1030)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.folderDisplay = QtWidgets.QLineEdit(self.groupBox_4)
        self.folderDisplay.setEnabled(False)
        self.folderDisplay.setAutoFillBackground(False)
        self.folderDisplay.setReadOnly(True)
        self.folderDisplay.setObjectName("folderDisplay")
        self.gridLayout.addWidget(self.folderDisplay, 1, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.groupBox_4)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 1, 2, 1, 1)
        self.filenameDisplay = QtWidgets.QLineEdit(self.groupBox_4)
        self.filenameDisplay.setObjectName("filenameDisplay")
        self.gridLayout.addWidget(self.filenameDisplay, 2, 1, 1, 1)
        self.calibBrowseButton = QtWidgets.QPushButton(self.groupBox_4)
        self.calibBrowseButton.setObjectName("calibBrowseButton")
        self.gridLayout.addWidget(self.calibBrowseButton, 0, 2, 1, 1)
        self.saveButton = QtWidgets.QPushButton(self.groupBox_4)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 2, 2, 1, 1)
        self.calibFileDisp = QtWidgets.QLineEdit(self.groupBox_4)
        self.calibFileDisp.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibFileDisp.sizePolicy().hasHeightForWidth())
        self.calibFileDisp.setSizePolicy(sizePolicy)
        self.calibFileDisp.setText("")
        self.calibFileDisp.setPlaceholderText("")
        self.calibFileDisp.setObjectName("calibFileDisp")
        self.gridLayout.addWidget(self.calibFileDisp, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 4, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.avgsSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.avgsSpinBox.setObjectName("avgsSpinBox")
        self.gridLayout_2.addWidget(self.avgsSpinBox, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.connectBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.connectBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectBox.sizePolicy().hasHeightForWidth())
        self.connectBox.setSizePolicy(sizePolicy)
        self.connectBox.setCheckable(True)
        self.connectBox.setTristate(False)
        self.connectBox.setObjectName("connectBox")
        self.gridLayout_2.addWidget(self.connectBox, 0, 1, 1, 1)
        self.intSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intSpinBox.sizePolicy().hasHeightForWidth())
        self.intSpinBox.setSizePolicy(sizePolicy)
        self.intSpinBox.setObjectName("intSpinBox")
        self.gridLayout_2.addWidget(self.intSpinBox, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.acqBckgButton = QtWidgets.QPushButton(self.groupBox)
        self.acqBckgButton.setObjectName("acqBckgButton")
        self.gridLayout_8.addWidget(self.acqBckgButton, 0, 0, 1, 1)
        self.acqINButton = QtWidgets.QPushButton(self.groupBox)
        self.acqINButton.setObjectName("acqINButton")
        self.gridLayout_8.addWidget(self.acqINButton, 1, 0, 1, 1)
        self.acqLaserButton = QtWidgets.QPushButton(self.groupBox)
        self.acqLaserButton.setObjectName("acqLaserButton")
        self.gridLayout_8.addWidget(self.acqLaserButton, 0, 1, 1, 1)
        self.acqOUTButton = QtWidgets.QPushButton(self.groupBox)
        self.acqOUTButton.setObjectName("acqOUTButton")
        self.gridLayout_8.addWidget(self.acqOUTButton, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.INPLthresh = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.INPLthresh.setObjectName("INPLthresh")
        self.gridLayout_6.addWidget(self.INPLthresh, 2, 1, 1, 1)
        self.laserthresh = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.laserthresh.setObjectName("laserthresh")
        self.gridLayout_6.addWidget(self.laserthresh, 2, 0, 1, 1)
        self.OUTPLthresh = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.OUTPLthresh.setObjectName("OUTPLthresh")
        self.gridLayout_6.addWidget(self.OUTPLthresh, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 0, 0, 1, 1)
        self.calcPLQEButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcPLQEButton.sizePolicy().hasHeightForWidth())
        self.calcPLQEButton.setSizePolicy(sizePolicy)
        self.calcPLQEButton.setObjectName("calcPLQEButton")
        self.gridLayout_7.addWidget(self.calcPLQEButton, 0, 1, 1, 1)
        self.PLQEdisplay = QtWidgets.QLineEdit(self.groupBox_3)
        self.PLQEdisplay.setEnabled(True)
        self.PLQEdisplay.setReadOnly(True)
        self.PLQEdisplay.setObjectName("PLQEdisplay")
        self.gridLayout_7.addWidget(self.PLQEdisplay, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.groupBox_LaserPlot = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_LaserPlot.sizePolicy().hasHeightForWidth())
        self.groupBox_LaserPlot.setSizePolicy(sizePolicy)
        self.groupBox_LaserPlot.setMinimumSize(QtCore.QSize(0, 400))
        self.groupBox_LaserPlot.setBaseSize(QtCore.QSize(0, 800))
        self.groupBox_LaserPlot.setObjectName("groupBox_LaserPlot")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_LaserPlot)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.acqBckgButton.clicked.connect(self.acquireBckgSlot)
        self.calcPLQEButton.clicked.connect(self.calcPLQESlot)
        self.acqINButton.clicked.connect(self.acquireINSlot)
        self.acqOUTButton.clicked.connect(self.acquireOUTSlot)
        # self.connectBox.toggled['bool'].connect(MainWindow.connectSpecSlot)
        self.saveButton.clicked.connect(self.savefileSlot)
        self.calibBrowseButton.clicked.connect(self.calibBrowseSlot)
        self.acqLaserButton.clicked.connect(self.acquireLaserSlot)
        self.browseButton.clicked.connect(self.browseSlot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Saving"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.calibBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.label_2.setText(_translate("MainWindow", "Filename"))
        self.label.setText(_translate("MainWindow", "Folder"))
        self.label_7.setText(_translate("MainWindow", "Calibration"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Spectrometer"))
        self.label_3.setText(_translate("MainWindow", "Integration (ms)"))
        self.connectBox.setText(_translate("MainWindow", "Connect"))
        self.label_5.setText(_translate("MainWindow", "USB4000"))
        self.label_4.setText(_translate("MainWindow", "Avgs"))
        self.groupBox.setTitle(_translate("MainWindow", "Acquisition"))
        self.acqBckgButton.setText(_translate("MainWindow", "Acquire bckg"))
        self.acqINButton.setText(_translate("MainWindow", "Sample in beam"))
        self.acqLaserButton.setText(_translate("MainWindow", "Laser in"))
        self.acqOUTButton.setText(_translate("MainWindow", "Sample out of beam"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Signal Detection"))
        self.label_6.setText(_translate("MainWindow", "Laser Thresh"))
        self.label_9.setText(_translate("MainWindow", "OUTPL Thresh"))
        self.label_8.setText(_translate("MainWindow", "INPL Thresh"))
        self.pushButton.setText(_translate("MainWindow", "Signal Detect"))
        self.calcPLQEButton.setText(_translate("MainWindow", "Calculate PLQE"))
        self.groupBox_LaserPlot.setTitle(_translate("MainWindow", "Spectra"))

